### ISSUE TITLE
Allow subscription without watchlist entries [FEAT]

### ISSUE THREAD

**Issue by johnkennyuk** [resort-io/nyaa-watcher#23]
### Additional Information

Could we make subscriptions watchlist entries optional? This change would effectively provide a wildcard RSS monitor for specific users. Currently, the TUI doesn’t allow skipping past subscription watchlist items when necessary, I eventually used the username value for a watchlist tag value which seemed to work for now. Still having a wildcard watchlist option would be ideal. 

### Benefits of the Feature

By implementing this feature, users can subscribe to all uploads from specific uploaders, effectively creating an uploader wildcard subscription

### Code Changes

I am not yet a proficient python developer hence this request. I had another play today and ended up just using the username as a watchlist tag value which seemed to do the job but having a way to wildcard usernames would be ideal.

**Comment by resort-io** [comment]
This is a great idea. I can definitely implement this.

Also about the bug, it sounds like the watcher isn't reading the JSON properly. I'll look into this.

**Comment by johnkennyuk** [comment]
This would be ideal if implemented,
