### ISSUE TITLE
Torrent filename got truncated for some titles? [BUG] 

### ISSUE THREAD

**Issue by johnkennyuk** [resort-io/nyaa-watcher#24]
### Bug/Issue

I ran v1.20 today which worked but some of the downloaded torrents seemed to have there filenames truncated causing the file to lose the file extension too? I'm assuming a string limit must be at play somewhere?

This title was fine:

[[Yameii] DEAD DEAD DEMONS DEDEDEDE DESTRUCTION - S01E09 [English Dub] [CR WEB-DL 1080p] [4CD3F265]](https://nyaa.si/view/1850651)

But this got truncated:

[[Yameii] BARTENDER Glass of God - S01E01 [English Dub] [CR WEB-DL 1080p] [8B740E5E] (Bartender: Kami no Glass)](https://nyaa.si/view/1850594)

### Debug Log Message

The logs didn't show any problems, 

### Code Changes

As mentioned I'm assuming the variable used for the writing of the fetched torrent may have a limit wherever it's set, also I did wonder if the torrents actual filename could be better to use as it seems the codes using the torrents title for the filename rather than the  .torrents actual download filename which from what I could see was a lower character count than the title? (to see what I mean manually download the torrent file from the url above to see the default filename, it drops the bracketed text from the downloads filename so isn't as long as the title text)

**Comment by resort-io** [comment]
The character limit would definitely interfere with the longer named series, I had not thought of that.

I could implement something that uses a simple format such as, '[Uploader] Series Name - S01E01'?
The video quality could also be included into the file name, but that may interfere with the long titles.

**Comment by johnkennyuk** [comment]
If you look at non rss nyaa torrent pages the download torrent filename seems shorter than the title on the page itself, could that filename variable be used? I've yet to experiment myself yet to see if it reduces the character count enough, but I'm assuming it's shorter for a reason, I'm thinking it could work?

**Comment by resort-io** [comment]
> If you look at non rss nyaa torrent pages the download torrent filename seems shorter than the title on the page itself, could that filename variable be used? I've yet to experiment myself yet to see if it reduces the character count enough, but I'm assuming it's shorter for a reason, I'm thinking it could work?

It looks like the Nyaa website removes the encoding info from the title when you download a torrent file directly. I could implement the same thing where the files are named as `[Username] Series - S01E01.torrent`.
Is that what you're thinking?
